### PR TITLE
Upgrade Decidim to 0.26

### PR DESCRIPTION
**Pull request by NicoleSo13**
This PR upgrades the application to Decidim version 0.26.
Release notes: https://github.com/decidim/decidim/releases/tag/v0.26.0

On deploy it will require to execute the following commands:

- Upgrade server's Ruby version to 2.7.5
- For locked users are present in global search, to update the search and make them disappear, Run in a bin/rails console or create a migration with:
  `Decidim::User.find_each(&:try_update_index_for_search_resource)`
- For fixing statistic in comments. There's a rake task that you need to run:
  `bin/rails decidim_comments:update_participatory_process_in_comments`
- For Base64 images migration run the following task:
  `bin/rails decidim:active_storage_migrations:migrate_inline_images_to_active_storage[admin_email]`

### CODE REVIEW

**Review by tramuntanal — DISMISSED** [review]
LGTM @NicoleSo13 !

**Review by laurajaime — CHANGES_REQUESTED** [review]
@NicoleSo13 be careful!

This app have overrides and decorators.

You must check it and do changes if is needed.

Can you review it, please?

**Comment by laurajaime** [comment]
@NicoleSo13 can you add decorators and overrides to README?

**Comment by laurajaime** [comment]
can you update Ruby version to 2.7.5 @NicoleSo13 ?

**Comment by NicoleSo13** [comment]
Ruby bumped to 2.7.5

**Review by laurajaime — APPROVED** [review]
Great! Good job @NicoleSo13 !!

**Pull request merged**
